################################  Exclusions  ##################################
exclude = [
  'in-a-box.cloud',
  'testbed.osism.xyz',
  'testbed.osism.xyz',
  'http://xn--hvg/',
  'https://xn--hvg/',
  'www.supermicro.com',
  'goteleport.com'
]
################################  Requests  ####################################
insecure = true
